welcome: "Hello! With this bot, you can fill out the form, which will be posted to the channel, if admins accept it."
templates:
  - title: "Form for posting to channel"
    description: "This form will be posted to channel if accepted."
    complete: "Thank you for completing the form, the bot will notify you when it will be accepted or rejected."
    entries:
    - mode: "text"
      title: "Event title"
      incorrect: "You entered an incorrect title, please try again."
      description: "Please, enter the title for your event."
    - mode: "date"
      title: "Event Date"
      incorrect: "It was an incorrect date, please try again."
      description: "Please enter the date in DD.MM.YYYY format (e.g. 31.05.2024)."
    - mode: "oneof"
      title: "Where will your event take place?"
      incorrect: "Please, try again and use the buttons."
      description: "Please select the answer from one of the buttons."
      options:
        - "Outdoor"
        - "Indoor"
